name: build utility for data processing

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: data processing executable
        run: gcc -o clean clean.c cleantext.c

      - name: outputting the cleaned wbcd.txt file
        run: ./clean < wbcd.txt > cleaned_wbcd.txt