name: build utility for data processing

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: data processing executable
        run: make clean

      - name: upload cleaned wbcd.txt file
        uses: actions/upload-artifact@v4
        with:
          name: cleaned wbcd.txt file
          path: ./clean < wbcd.txt > cleaned_wbcd.txt